name: 'coffee-shop-backend'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    mem_limit: 2g
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./keys:/app/keys
    mem_limit: 512m
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head && gunicorn
