"""create user and otp models

Revision ID: 2f2836c35c4e
Revises: a143e6c04b55
Create Date: 2025-06-09 22:28:25.243276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2836c35c4e'
down_revision: Union[str, None] = 'a143e6c04b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['coffee_shop_backend.user_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='coffee_shop_backend'
    )
    op.create_index(op.f('ix_coffee_shop_backend_user_created_at'), 'user', ['created_at'], unique=False, schema='coffee_shop_backend')
    op.create_index(op.f('ix_coffee_shop_backend_user_phone_number'), 'user', ['phone_number'], unique=True, schema='coffee_shop_backend')
    op.create_index(op.f('ix_coffee_shop_backend_user_role_id'), 'user', ['role_id'], unique=False, schema='coffee_shop_backend')
    op.create_index(op.f('ix_coffee_shop_backend_user_username'), 'user', ['username'], unique=True, schema='coffee_shop_backend')
    op.create_table('otp',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['coffee_shop_backend.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'user_id', name='unique_otp_code_user_id'),
    schema='coffee_shop_backend'
    )
    op.create_index(op.f('ix_coffee_shop_backend_otp_code'), 'otp', ['code'], unique=False, schema='coffee_shop_backend')
    op.create_index(op.f('ix_coffee_shop_backend_otp_created_at'), 'otp', ['created_at'], unique=False, schema='coffee_shop_backend')
    op.create_index(op.f('ix_coffee_shop_backend_otp_user_id'), 'otp', ['user_id'], unique=False, schema='coffee_shop_backend')
    op.drop_constraint(op.f('user_role_alias_key'), 'user_role', schema='coffee_shop_backend', type_='unique')
    op.create_index(op.f('ix_coffee_shop_backend_user_role_alias'), 'user_role', ['alias'], unique=True, schema='coffee_shop_backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coffee_shop_backend_user_role_alias'), table_name='user_role', schema='coffee_shop_backend')
    op.create_unique_constraint(op.f('user_role_alias_key'), 'user_role', ['alias'], schema='coffee_shop_backend', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_coffee_shop_backend_otp_user_id'), table_name='otp', schema='coffee_shop_backend')
    op.drop_index(op.f('ix_coffee_shop_backend_otp_created_at'), table_name='otp', schema='coffee_shop_backend')
    op.drop_index(op.f('ix_coffee_shop_backend_otp_code'), table_name='otp', schema='coffee_shop_backend')
    op.drop_table('otp', schema='coffee_shop_backend')
    op.drop_index(op.f('ix_coffee_shop_backend_user_username'), table_name='user', schema='coffee_shop_backend')
    op.drop_index(op.f('ix_coffee_shop_backend_user_role_id'), table_name='user', schema='coffee_shop_backend')
    op.drop_index(op.f('ix_coffee_shop_backend_user_phone_number'), table_name='user', schema='coffee_shop_backend')
    op.drop_index(op.f('ix_coffee_shop_backend_user_created_at'), table_name='user', schema='coffee_shop_backend')
    op.drop_table('user', schema='coffee_shop_backend')
    # ### end Alembic commands ###
