"""add session model

Revision ID: 0e02db805c63
Revises: 2f2836c35c4e
Create Date: 2025-06-10 02:16:03.402893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e02db805c63'
down_revision: Union[str, None] = '2f2836c35c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_terminated', sa.Boolean(), nullable=False),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['coffee_shop_backend.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='coffee_shop_backend'
    )
    op.create_index(op.f('ix_coffee_shop_backend_session_user_id'), 'session', ['user_id'], unique=False, schema='coffee_shop_backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coffee_shop_backend_session_user_id'), table_name='session', schema='coffee_shop_backend')
    op.drop_table('session', schema='coffee_shop_backend')
    # ### end Alembic commands ###
